# Generated by Django 5.1.2 on 2025-10-21 12:24

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at'], 'verbose_name': 'מועמדות', 'verbose_name_plural': 'מועמדויות'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at'], 'verbose_name': 'משרה', 'verbose_name_plural': 'משרות'},
        ),
        migrations.AddField(
            model_name='application',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='נבדק ב'),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'ממתין'), ('accepted', 'התקבל'), ('rejected', 'נדחה'), ('withdrawn', 'משך מועמדות')], default='pending', max_length=20, verbose_name='סטטוס'),
        ),
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='תאריך יעד'),
        ),
        migrations.AddField(
            model_name='job',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'קל'), ('medium', 'בינוני'), ('hard', 'קשה')], default='medium', max_length=20, verbose_name='רמת קושי'),
        ),
        migrations.AddField(
            model_name='job',
            name='max_applicants',
            field=models.PositiveIntegerField(default=10, help_text='כמה מועמדים מקסימום יכולים להגיש מועמדות', verbose_name='מספר מקסימלי של מועמדים'),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'טיוטה'), ('open', 'פתוח'), ('closed', 'סגור'), ('filled', 'אויש')], default='draft', max_length=20, verbose_name='סטטוס'),
        ),
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True, help_text='למה אתה מתאים למשרה?', verbose_name='מכתב מקדים'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='הוגש ב'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='נוצר ב'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20, 'תיאור חייב להיות לפחות 20 תווים')], verbose_name='תיאור'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5, 'כותרת חייבת להיות לפחות 5 תווים')], verbose_name='כותרת'),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='עודכן ב'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', '-created_at'], name='jobs_applic_applica_a398e7_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', 'status'], name='jobs_applic_job_id_a25382_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['-created_at'], name='jobs_job_created_77460a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='jobs_job_status_7d017a_idx'),
        ),
    ]
