services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app        # live-reload during dev
    env_file:
      - .env          # load env vars
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: junior_markets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
